-- Public newsletter signup (landing footer CTA)
-- Apply: psql "$DATABASE_URL" -f apps/web/supabase/migrations/20260915_newsletter_public.sql

CREATE TABLE IF NOT EXISTS public.newsletter_subscribers (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email      text NOT NULL UNIQUE,
  source     text NOT NULL DEFAULT 'landing',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS newsletter_subscribers_created_at_idx
  ON public.newsletter_subscribers (created_at DESC);

ALTER TABLE public.newsletter_subscribers ENABLE ROW LEVEL SECURITY;

-- Public can insert newsletter emails (API uses DATABASE_URL / server role).
DROP POLICY IF EXISTS "Allow public insert newsletter" ON public.newsletter_subscribers;
CREATE POLICY "Allow public insert newsletter"
ON public.newsletter_subscribers
FOR INSERT
TO anon
WITH CHECK (email IS NOT NULL);

DROP POLICY IF EXISTS "Allow public read newsletter" ON public.newsletter_subscribers;
CREATE POLICY "Allow public read newsletter"
ON public.newsletter_subscribers
FOR SELECT
TO anon
USING (true);
