-- VIP Waitlist signup (public.waitlist)
-- Apply: psql "$DATABASE_URL" -f apps/web/supabase/migrations/20260819_waitlist_public.sql

CREATE TABLE IF NOT EXISTS public.waitlist (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email      text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS waitlist_created_at_idx
  ON public.waitlist (created_at DESC);

ALTER TABLE public.waitlist ENABLE ROW LEVEL SECURITY;

-- Public can insert waitlist emails.
DROP POLICY IF EXISTS "Allow public insert waitlist" ON public.waitlist;
CREATE POLICY "Allow public insert waitlist"
ON public.waitlist
FOR INSERT
TO anon
WITH CHECK (email IS NOT NULL);

-- Allow public read access (used by server to compute queue via inserts/returns).
-- Note: our API does not list the full table, it returns only the inserted row id.
DROP POLICY IF EXISTS "Allow public read waitlist" ON public.waitlist;
CREATE POLICY "Allow public read waitlist"
ON public.waitlist
FOR SELECT
TO anon
USING (true);

-- Service-role bypasses RLS.

