'use client';

import { LegalDoc, LegalH2 } from '@/components/legal/LegalDoc';

export default function VillkorContent() {
  return (
    <LegalDoc doc="terms" updated="August 10, 2026">
      <p>
        Welcome to clikd: (<a href="https://clikd.app">https://clikd.app</a>), operated by Cheriie
        AB (org. nr: 559527-2393, VAT: SE559527239301, &quot;we&quot;, &quot;us&quot;,
        &quot;our&quot;). These Terms of Service (&quot;Terms&quot;, &quot;Agreement&quot;) govern
        your access to and use of the website, mobile applications, social media planning tools, bio
        storefronts, member communities, AI copilot features, custom domain services, and associated
        services (collectively, the &quot;Service&quot;).
      </p>
      <p>
        By creating an account, accessing, or using the Service, you agree to be bound by this
        Agreement. If you do not agree to these Terms, you must not use the Service.
      </p>

      <LegalH2 section="termsS1" />
      <p>
        clikd: is an all-in-one creator engine and workspace platform enabling creators to plan
        social media content, host link-in-bio storefronts, sell digital products and courses, host
        member communities, link custom domains, and accept mobile payments.
      </p>

      <LegalH2 section="termsS2" />
      <p>
        To enable multi-channel social media planning, cross-posting, messaging, and analytics,
        clikd: integrates with official third-party APIs. By connecting your accounts, you agree to
        comply with the terms of each respective platform:
      </p>

      <h3 className="font-outfit font-extrabold text-base text-slate-900 tracking-tight mt-4 mb-2">
        A. OpenAI API &amp; AI Copilot Suite
      </h3>
      <ul>
        <li>The Service provides AI-assisted content tools powered by OpenAI.</li>
        <li>
          You agree not to use the AI Copilot to generate hate speech, spam, fraudulent claims,
          adult content, or material violating third-party copyrights.
        </li>
        <li>
          Output generated by AI is provided &quot;as-is&quot;. You are responsible for reviewing
          AI-generated captions and responses before publishing.
        </li>
      </ul>

      <h3 className="font-outfit font-extrabold text-base text-slate-900 tracking-tight mt-4 mb-2">
        B. Pinterest API
      </h3>
      <p>
        By connecting Pinterest accounts, you agree to comply with Pinterest Developer Terms and
        Pinterest Community Guidelines. You represent that all Pins scheduled through clikd: link to
        legitimate, non-spam destination URLs.
      </p>

      <h3 className="font-outfit font-extrabold text-base text-slate-900 tracking-tight mt-4 mb-2">
        C. TikTok API, Meta &amp; YouTube
      </h3>
      <p>
        You agree to comply with TikTok&apos;s Developer Terms, Meta&apos;s Platform Terms
        (including Instagram DM policies), and the{' '}
        <a href="https://www.youtube.com/t/terms" target="_blank" rel="noopener noreferrer">
          YouTube Terms of Service
        </a>
        .
      </p>

      <LegalH2 section="termsS3" />
      <ul>
        <li>
          <strong>Domain Ownership:</strong> PRO plan users linking a custom domain (e.g.,
          yourname.se or hub.yourname.se) represent and warrant that they own or have explicit rights
          to use the domain name.
        </li>
        <li>
          <strong>DNS Configuration:</strong> The User is responsible for pointing their DNS records
          (A Record / CNAME) to our edge infrastructure as instructed. clikd: provides automated SSL
          certificate issuance via Vercel API.
        </li>
        <li>
          <strong>Prohibited Domain Uses:</strong> Custom domains connected to clikd: must not be
          used for phishing, brand impersonation, malware distribution, or illegal activities. We
          reserve the right to immediately remove any custom domain violating this clause.
        </li>
      </ul>

      <LegalH2 section="termsS4" />
      <h3 className="font-outfit font-extrabold text-base text-slate-900 tracking-tight mt-4 mb-2">
        A. Creator as Seller of Record
      </h3>
      <p>
        Creators who sell digital products, memberships, or coaching slots act as the Seller of
        Record for those products. clikd: (operated by Cheriie AB) provides software infrastructure
        and payment gateway integrations (Stripe, Swish, Vipps) but is not the seller or publisher of
        Creator products.
      </p>

      <h3 className="font-outfit font-extrabold text-base text-slate-900 tracking-tight mt-4 mb-2">
        B. Fees and Payouts
      </h3>
      <ul>
        <li>
          Depending on your plan (Starter, Creator, Pro), clikd: charges a platform fee (0% – 8%) per
          transaction. Pro/Agency plan users enjoy 0% platform fees.
        </li>
        <li>
          Earnings are held in your clikd: creator wallet balance and transferred to your bank
          account upon request or according to automated payout schedules.
        </li>
      </ul>

      <h3 className="font-outfit font-extrabold text-base text-slate-900 tracking-tight mt-4 mb-2">
        C. Refunds and Taxes
      </h3>
      <ul>
        <li>
          Creators are responsible for handling refund requests and complying with consumer
          protection laws.
        </li>
        <li>
          Creators are solely responsible for reporting and remitting applicable local sales tax,
          income tax, and Value Added Tax (VAT) (e.g., 6% / 25% Nordic VAT). clikd: provides
          automated VAT calculation and Fortnox accounting sync tools to assist compliance.
        </li>
      </ul>

      <LegalH2 section="termsS5" />
      <p>You agree not to use the Service to:</p>
      <ul>
        <li>Publish or distribute illegal, defamatory, hateful, or infringing content.</li>
        <li>Impersonate any person or entity or misrepresent domain ownership.</li>
        <li>
          Attempt to reverse engineer, disrupt, or compromise the security of the Service.
        </li>
      </ul>

      <LegalH2 section="termsS6" />
      <p className="uppercase tracking-wide text-[13px] sm:text-sm leading-relaxed">
        To the maximum extent permitted by applicable law, Cheriie AB and clikd: shall not be liable
        for any indirect, incidental, or consequential damages, loss of profits, or data arising from
        your use of the Service, third-party API disruptions (Instagram, TikTok, Pinterest, OpenAI),
        or custom domain DNS misconfigurations.
      </p>

      <LegalH2 section="termsS7" />
      <p>
        These Terms shall be governed by and construed in accordance with the laws of Sweden. Any
        dispute shall be submitted to the exclusive jurisdiction of the District Court of Stockholm
        (Stockholms tingsrätt).
      </p>

      <LegalH2 section="termsS8" />
      <ul>
        <li>
          <strong>Legal Entity:</strong> Cheriie AB
        </li>
        <li>
          <strong>Org. nr:</strong> 559527-2393
        </li>
        <li>
          <strong>VAT Registration Number:</strong> SE559527239301
        </li>
        <li>
          <strong>Registered Address:</strong> Sturegatan 18 A, 211 50 Malmö, Sweden
        </li>
        <li>
          <strong>Official Website:</strong>{' '}
          <a href="https://clikd.app">https://clikd.app</a>
        </li>
        <li>
          <strong>General, Legal &amp; Privacy Inquiries:</strong>{' '}
          <a href="mailto:hello@clikd.app">hello@clikd.app</a>
        </li>
      </ul>
    </LegalDoc>
  );
}
