import sql from '@/app/api/utils/sql';

function normalizeEmail(raw: string) {
  return raw.trim().toLowerCase();
}

function isValidEmail(email: string) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
}

/**
 * POST /api/newsletter
 *
 * Body: { email: string; source?: string }
 * Returns: { ok: true, alreadySubscribed?: boolean }
 */
export async function POST(request: Request) {
  if (!process.env.DATABASE_URL?.trim()) {
    return Response.json({ error: 'database_offline' }, { status: 503 });
  }

  try {
    const body: unknown = await request.json().catch(() => null);
    const emailRaw =
      typeof body === 'object' && body != null ? (body as { email?: unknown }).email : undefined;
    const sourceRaw =
      typeof body === 'object' && body != null ? (body as { source?: unknown }).source : undefined;
    const email = typeof emailRaw === 'string' ? normalizeEmail(emailRaw) : '';
    const source =
      typeof sourceRaw === 'string' && sourceRaw.trim()
        ? sourceRaw.trim().slice(0, 64)
        : 'landing';

    if (!email) {
      return Response.json({ error: 'email_required' }, { status: 400 });
    }
    if (!isValidEmail(email)) {
      return Response.json({ error: 'invalid_email' }, { status: 400 });
    }

    // Ensure schema exists (heal) then upsert subscriber.
    await sql`
      CREATE TABLE IF NOT EXISTS public.newsletter_subscribers (
        id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email      text NOT NULL UNIQUE,
        source     text NOT NULL DEFAULT 'landing',
        created_at timestamptz NOT NULL DEFAULT now()
      )
    `;

    const existing = await sql`
      SELECT id FROM public.newsletter_subscribers WHERE email = ${email} LIMIT 1
    `;

    if (existing.length > 0) {
      return Response.json({ ok: true, alreadySubscribed: true });
    }

    await sql`
      INSERT INTO public.newsletter_subscribers (email, source)
      VALUES (${email}, ${source})
    `;

    return Response.json({ ok: true, alreadySubscribed: false });
  } catch (err) {
    console.error('[newsletter] POST failed', err);
    return Response.json({ error: 'newsletter_failed' }, { status: 500 });
  }
}
